#!/usr/bin/env node
/**
 * Regenerates packages/ui/icons.ts from the design prototype's icon geometry.
 *
 * The prototype draws icons as inline SVG (`js/icons.js` → ICON_PATHS). React Native has no
 * SVG, so this extracts the *geometry* — a design asset, like the logo PNG — and normalises
 * every element (path, circle, rect) into a path string that Skia can draw. No prototype
 * code is carried over; only coordinates.
 *
 * Usage:  node scripts/port-icons.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import vm from 'node:vm';

const here = dirname(fileURLToPath(import.meta.url));
const PROTOTYPE_ICONS = resolve(
  here,
  '../../# BakeFlow frontend design/export/bakeflow-frontend/js/icons.js',
);
const OUT = resolve(here, '../packages/ui/icons.ts');

const source = readFileSync(PROTOTYPE_ICONS, 'utf8');
const sandbox = {};
vm.runInNewContext(`${source}\n;globalThis.__ICONS__ = ICON_PATHS;`, sandbox);
const icons = sandbox.__ICONS__;
if (!icons) throw new Error('ICON_PATHS not found in prototype icons.js');

const attrs = (tag) => {
  const out = {};
  for (const [, k, v] of tag.matchAll(/([a-zA-Z-]+)="([^"]*)"/g)) out[k] = v;
  return out;
};
const num = (v, fallback = 0) => (v === undefined ? fallback : Number(v));
const fmt = (n) => String(Math.round(n * 1000) / 1000);

function circleToPath({ cx, cy, r }) {
  const x = num(cx), y = num(cy), rad = num(r);
  return `M${fmt(x - rad)} ${fmt(y)}a${fmt(rad)} ${fmt(rad)} 0 1 0 ${fmt(rad * 2)} 0a${fmt(rad)} ${fmt(rad)} 0 1 0 ${fmt(-rad * 2)} 0Z`;
}

function rectToPath(a) {
  const x = num(a.x), y = num(a.y), w = num(a.width), h = num(a.height);
  const r = Math.min(num(a.rx, num(a.ry)), w / 2, h / 2);
  if (!r) return `M${fmt(x)} ${fmt(y)}h${fmt(w)}v${fmt(h)}h${fmt(-w)}Z`;
  return [
    `M${fmt(x + r)} ${fmt(y)}`,
    `h${fmt(w - 2 * r)}`, `a${fmt(r)} ${fmt(r)} 0 0 1 ${fmt(r)} ${fmt(r)}`,
    `v${fmt(h - 2 * r)}`, `a${fmt(r)} ${fmt(r)} 0 0 1 ${fmt(-r)} ${fmt(r)}`,
    `h${fmt(-(w - 2 * r))}`, `a${fmt(r)} ${fmt(r)} 0 0 1 ${fmt(-r)} ${fmt(-r)}`,
    `v${fmt(-(h - 2 * r))}`, `a${fmt(r)} ${fmt(r)} 0 0 1 ${fmt(r)} ${fmt(-r)}`, 'Z',
  ].join('');
}

const result = {};
const skipped = [];
for (const [name, markup] of Object.entries(icons)) {
  const parts = [];
  for (const [tag, kind] of markup.matchAll(/<(path|circle|rect)\b[^>]*\/?>/g)) {
    const a = attrs(tag);
    const d = kind === 'path' ? a.d : kind === 'circle' ? circleToPath(a) : rectToPath(a);
    if (!d) continue;
    const part = { d };
    if (a.fill === 'currentColor') part.fill = true;
    if (a.stroke === 'none') part.stroke = false;
    if (a.opacity !== undefined) part.opacity = Number(a.opacity);
    parts.push(part);
  }
  if (parts.length === 0) skipped.push(name);
  else result[name] = parts;
}

const names = Object.keys(result).sort();
const body = names
  .map((n) => `  ${/^[a-zA-Z_$][\w$]*$/.test(n) ? n : JSON.stringify(n)}: ${JSON.stringify(result[n])},`)
  .join('\n');

writeFileSync(
  OUT,
  `/* GENERATED by scripts/port-icons.mjs from the design prototype's icon geometry — do not
   edit by hand. Re-run the script after changing icons in the prototype.
   24×24 grid, 1.65 stroke, round caps and joins. Every element is normalised to a path. */

export interface IconPart {
  d: string;
  /** Filled with the icon colour (default: stroked only). */
  fill?: boolean;
  /** \`false\` when the prototype draws this element with \`stroke="none"\`. */
  stroke?: boolean;
  opacity?: number;
}

export const ICONS = {
${body}
} as const satisfies Record<string, readonly IconPart[]>;

export type IconName = keyof typeof ICONS;
`,
);

console.log(`wrote ${names.length} icons → ${OUT}`);
if (skipped.length) console.log(`skipped (no drawable geometry): ${skipped.join(', ')}`);
